# log config
logging:
  config: classpath:logback.xml


  ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:9090/xxl-job-admin
    ### xxl-job, access token
    accessToken:
    ### xxl-job executor appname
    executor:
      appname: xxl-job-executor-flux
      ### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
      address:
      ### xxl-job executor server-info
      ip:
      port: 9999
      ### xxl-job executor log-path
      logpath: E:\\share-wifi2\\share-schedule\\jobhandler
      ### xxl-job executor log-retention-days
      logretentiondays: 30


  ### mybatis
mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  #mybatis.type-aliases-package=com.xxl.job.admin.core.model

  ### xxl-job, datasource
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/share-wifi?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    ### datasource-pool
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      max-lifetim: 900000
      connection-timeout: 10000
      connection-test-query: SELECT 1
